# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qgs2postgis
                                 A QGIS plugin
 Module to upload data into existing datasets to postgis fastly
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-21
        copyright            : (C) 2025 by Martin Reger
        email                : martin150897@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load qgs2postgis class from file qgs2postgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgs2postgis import qgs2postgis
    return qgs2postgis(iface)
